name: Build Python 3.12 for iOS (arm64) and package .deb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 60
    concurrency:
      group: ios-python3.12-arm64-${{ github.ref }}
      cancel-in-progress: true
    env:
      PY_VER: 3.12.5
      LIBFFI_VER: 3.4.4
      MIN_IOS: 12.0
      OPENSSL_BRANCH: OpenSSL_1_1_1-stable

    steps:
      # ---------------------------------------------
      # Checkout repository
      # ---------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------------------------
      # Discover iOS SDK version (for caching/debug)
      # ---------------------------------------------
      - name: Discover SDK version
        id: sdk
        run: |
          echo "version=$(xcrun --sdk iphoneos --show-sdk-version)" >> "$GITHUB_OUTPUT"

      # ---------------------------------------------
      # Restore dependency cache (OpenSSL, libffi)
      # ---------------------------------------------
      - name: Restore deps cache
        uses: actions/cache@v4
        with:
          path: |
            work/deps/openssl-ios
            work/deps/libffi-ios
          key: ios-${{ runner.os }}-sdk-${{ steps.sdk.outputs.version }}-openssl-${{ env.OPENSSL_BRANCH }}-libffi-${{ env.LIBFFI_VER }}-hash-${{ hashFiles('scripts/*.sh', '.github/workflows/python3.12-ios-arm64.yml') }}
          restore-keys: |
            ios-${{ runner.os }}-sdk-${{ steps.sdk.outputs.version }}-openssl-${{ env.OPENSSL_BRANCH }}-libffi-${{ env.LIBFFI_VER }}-
            ios-${{ runner.os }}-sdk-${{ steps.sdk.outputs.version }}-

      # ---------------------------------------------
      # Install required build tools via Homebrew
      # ---------------------------------------------
      - name: Install build tools
        run: |
          bash scripts/install-build-tools.sh

      # ---------------------------------------------
      # Prepare host Python 3.12 used by CPython's build
      # ---------------------------------------------
      - name: Set up Python 3.12 for host build
        id: py
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ---------------------------------------------
      # Build dependencies and CPython, then package .deb
      # (Behavior identical to previous inline script)
      # ---------------------------------------------
      - name: Build Python 3.12 for iOS and package .deb
        env:
          PY_VER: 3.12.5
          LIBFFI_VER: 3.4.4
          MIN_IOS: 12.0
          OPENSSL_BRANCH: OpenSSL_1_1_1-stable
        run: |
          set -euxo pipefail
          # Ensure identical env scope as original inline block
          source scripts/common-env.sh

          # 1) OpenSSL 1.1.1 (stable)
          bash scripts/build-openssl.sh

          # 2) libffi (static)
          bash scripts/build-libffi.sh

          # 3) CPython 3.12 build and stage (pass host python explicitly)
          PYTHON_FOR_BUILD="${{ steps.py.outputs.python-path }}" bash scripts/build-python.sh

          # 4) .deb packaging
          bash scripts/package-dpkg.sh

      # ---------------------------------------------
      # Upload artifact (.deb)
      # ---------------------------------------------
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: python3.12_iphoneos-arm
          path: work/python3.12_*_iphoneos-arm.deb