# ==============================================================================
# Archived workflow: Old non-Theos Python 3.12 build
# This workflow has been replaced by the Theos-based packaging workflow
# at .github/workflows/theos-tweak.yml. Keeping this file for reference.
# ==============================================================================
name: (Archived) Build Python 3.12 for iOS (arm64) and package .deb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Note
        run: |
          echo "This workflow is archived. Use .github/workflows/theos-tweak.yml instead."
