name: Build Python 3.12 for iOS (arm64) and package .deb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      # ---------------------------------------------
      # Checkout repository
      # ---------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------------------------
      # Install required build tools via Homebrew
      # ---------------------------------------------
      - name: Install build tools
        run: |
          bash scripts/install-build-tools.sh

      # ---------------------------------------------
      # Prepare host Python 3.12 used by CPython's build
      # ---------------------------------------------
      - name: Set up Python 3.12 for host build
        id: py
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ---------------------------------------------
      # Build dependencies and CPython, then package .deb
      # (Behavior identical to previous inline script)
      # ---------------------------------------------
      - name: Build Python 3.12 for iOS and package .deb
        env:
          PY_VER: 3.12.5
          LIBFFI_VER: 3.4.4
          MIN_IOS: 12.0
          OPENSSL_BRANCH: OpenSSL_1_1_1-stable
        run: |
          set -euxo pipefail
          # 1) OpenSSL 1.1.1 (stable)
          bash scripts/build-openssl.sh

          # 2) libffi (static)
          bash scripts/build-libffi.sh
          # Ensure PKG_CONFIG_PATH is set in parent shell exactly as original
          export PKG_CONFIG_PATH="$DEPS/libffi-ios/usr/local/lib/pkgconfig:$DEPS/openssl-ios/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH:-}"

          # 3) CPython 3.12 build and stage (pass host python explicitly)
          PYTHON_FOR_BUILD="${{ steps.py.outputs.python-path }}" bash scripts/build-python.sh

          # 4) .deb packaging
          bash scripts/package-dpkg.sh

      # ---------------------------------------------
      # Upload artifact (.deb)
      # ---------------------------------------------
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: python3.12_iphoneos-arm
          path: work/python3.12_*_iphoneos-arm.deb
